apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: golang-lint
  namespace: tektonci
  description: |
    Lint golang source using golangci-lint
spec:
  params:
  - name: version
    description: golangci-lint version to use
    default: "v1.27.0"
  - name: flags
    description: flags to use for the golangci-lint run command
    default: --verbose
  - name: GOOS
    description: "running operating system target"
    default: linux
  - name: GOARCH
    description: "running architecture target"
    default: amd64
  - name: GO111MODULE
    description: "value of module support"
    default: auto
  resources:
    inputs:
      - name: source
        type: git
  steps:
  - name: lint
    image: golangci/golangci-lint:$(params.version)
    script: |
      #!/bin/sh
      set -ex
      cd /workspace/source/
      golangci-lint run $(params.flags)
    env:
    - name: GOPATH
      value: /workspace
    - name: GOOS
      value: "$(params.GOOS)"
    - name: GOARCH
      value: "$(params.GOARCH)"
    - name: GO111MODULE
      value: "$(params.GO111MODULE)"
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: yamllint
  namespace: tektonci
  description: |
    Lint yamls
spec:
  params:
  - name: folders
    description: The folders to lint with yamllint
  resources:
    inputs:
      - name: source
        type: git
  steps:
  - name: lint
    image: gcr.io/tekton-releases/dogfooding/yamllint:latest
    workingDir: $(resources.inputs.source.path)
    script: |
      #!/bin/sh
      set -ex
      yamllint $(params.folders)
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-push-kaniko
  namespace: tektonci
  description: |
    CI Job that builds a container images and pushes it to a CR using kaniko
spec:
  params:
  - name: IMAGE
    description: Name (reference) of the image to build.
  - name: DOCKERFILE
    description: Path to the Dockerfile to build.
    default: ./Dockerfile
  - name: CONTEXT
    description: The build context used by Kaniko.
    default: ./
  - name: EXTRA_ARGS
    default: ""
  - name: BUILDER_IMAGE
    description: The image on which builds will run
    default: gcr.io/kaniko-project/executor:latest
  resources:
    inputs:
    - name: source
      type: git
  results:
  - name: IMAGE_DIGEST
    description: Digest of the image just built.

  steps:
  - name: demo
    image: busybox
    script: |
      echo 'Hello Tekton WG!'
  - name: build-and-push
    workingDir: /workspace/source
    image: $(params.BUILDER_IMAGE)
    # specifying DOCKER_CONFIG is required to allow kaniko to detect docker credential
    # https://github.com/tektoncd/pipeline/pull/706
    env:
    - name: DOCKER_CONFIG
      value: /tekton/home/.docker
    command:
    - /kaniko/executor
    - $(params.EXTRA_ARGS)
    - --dockerfile=$(params.DOCKERFILE)
    - --context=$(resources.inputs.source.path)/$(params.CONTEXT)  # The user does not need to care the workspace and the source.
    - --destination=$(params.IMAGE)
    - --oci-layout-path=$(resources.inputs.source.path)/image-digest
    - --no-push
    - --verbosity=error
    securityContext:
      runAsUser: 0
  - name: write-digest
    workingDir: $(resources.inputs.source.path)
    image: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/imagedigestexporter:v0.11.1
    # output of imagedigestexport [{"name":"image","digest":"sha256:eed29..660"}]
    command: ["/ko-app/imagedigestexporter"]
    args:
    - -images=[{"name":"$(params.IMAGE)","type":"image","url":"$(params.IMAGE)","digest":"","OutputImageDir":"$(resources.inputs.source.path)/image-digest"}]
    - -terminationMessagePath=image-digested
  - name: digest-to-results
    workingDir: $(resources.inputs.source.path)
    image: stedolan/jq
    script: |
      cat image-digested | jq '.[0].digest' | tee /tekton/results/IMAGE_DIGEST
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: check-kind-label
  namespace: tektonci
  description: |
    Verifies that a PR has one valid kind label
spec:
  resources:
    inputs:
      - name: source
        type: git
      - name: pr
        type: pullRequest
    outputs:
      - name: pr
        type: pullRequest
  params:
  - name: labels
    description: The labels attached to the Pull Request
  volumes:
  - name: label-config-v2
    configMap:
      name: label-config-v2
  steps:
  - name: copy-pr-to-output
    image: busybox
    script: |
      #!/bin/sh
      mkdir -p $(outputs.resources.pr.path)
      cp -r $(inputs.resources.pr.path)/* $(outputs.resources.pr.path)/
  - name: install-pyyaml
    image: python:3-alpine
    script: |
      pip install pyyaml --user
  - name: check-labels
    image: python:3-alpine
    volumeMounts:
      - name: label-config-v2
        mountPath: /etc/config
    script: |
      #!/usr/bin/env python

      import json
      import yaml
      import sys

      prLabelsText = """$(params.labels)"""
      prLabels = json.loads(prLabelsText)
      labelNames = list(map(lambda e: e["name"], prLabels))
      kindLabels = list(filter(lambda e: "kind" in e, labelNames))

      availableLabels = None
      with open("/etc/config/labels.yaml", "r") as stream:
        availableLabels = yaml.safe_load(stream)["default"]["labels"]

      availableKindLabels = list(filter(lambda e: "kind/" in e["name"], availableLabels))
      availableKindNamesAndDescriptions = map(lambda e: "`" +str(e["name"])+ "`" + ":  " + str(e["description"]), availableKindLabels)

      comment_template=""
      if (len(kindLabels) > 1 or len(kindLabels) == 0):
        comment_template += """
      **This PR cannot be merged:** expecting exactly one kind/ label

      <details>

      Available `kind/` labels are:

      """

        for i in availableKindNamesAndDescriptions:
          comment_template += i + "\n"

        comment_template += """

      </details>
      """
        new_comment_path = "$(outputs.resources.pr.path)/comments/new.json"
        comment_body = dict(body=comment_template)
        with open(new_comment_path, "w") as comment:
          json.dump(comment_body, comment)

        # Check failed. Return exit code 1.
        sys.exit(1)
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: tekton-cd-configmap-trigger
  namespace: tektonci
  description: |
    Triggers a config map deployment by sending a JSON body to a tekton CD
    event listener. Behaves the same as the "configmap-cd-trigger" cronjob base.
spec:
  results:
  - name: event-listener-event-id
    description: The trigger event ID from the event listener response
  params:
  - name: sinkUrl
    description: Event listener sink URL
    default: http://el-tekton-cd.default.svc.cluster.local:8080
  - name: gitRepository
    description: The git repo that hosts the configmap
    default: github.com/andreafrittoli/plumbing
  - name: gitRevision
    description: The git revision tha to be deployed
    default: master
  - name: configPath
    description: The PATH to be deployed within the git repo
  - name: namespace
    description: The namespace where the config map should be deployed
  - name: clusterResource
    description: Name of the cluster resources to be used for deployment
    default: af-tekton-cadmin
  - name: configmapName
    description: The name of the config map to be created / updated
  - name: configmapKey
    description: The name of the config map key that will host the data
  - name: configmapDescription
    description: A description of the config map
  steps:
  - name: http-trigger
    image: curlimages/curl
    script: |
      cat <<EOF > /workspace/post-body.json
      {
        "trigger-template": "configmap",
        "params": {
          "git": {
            "repository": "$GIT_REPOSITORY",
            "revision": "$GIT_REVISION"
          },
          "target": {
            "namespace": "$NAMESPACE",
            "cluster-resource": "$CLUSTER_RESOURCE"
          },
          "configmap": {
              "description": "$CONFIGMAP_DESCRIPTION",
              "path": "$CONFIG_PATH",
              "name": "$CONFIGMAP_NAME",
              "key": "$CONFIGMAP_KEY"
          }
        }
      }
      EOF
      curl --retry-connrefused --retry 200 \
        --retry-delay 0 --retry-max-time 600 \
        --output /workspace/response-body.json \
        -d @/workspace/post-body.json $SINK_URL
    env:
      - name: SINK_URL
        value: $(params.sinkUrl)
      - name: GIT_REPOSITORY
        value: $(params.gitRepository)
      - name: GIT_REVISION
        value: $(params.gitRevision)
      - name: CONFIG_PATH
        value: $(params.configPath)
      - name: NAMESPACE
        value: $(params.namespace)
      - name: CLUSTER_RESOURCE
        value: $(params.clusterResource)
      - name: CONFIGMAP_NAME
        value: $(params.configmapName)
      - name: CONFIGMAP_KEY
        value: $(params.configmapKey)
      - name: CONFIGMAP_DESCRIPTION
        value: $(params.configmapDescription)
  - name: extract-id
    image: stedolan/jq
    script: |
      echo "Extracting Event ID from:"
      cat /workspace/response-body.json

      cat /workspace/response-body.json | jq -r '.eventID' > $(results.event-listener-event-id.path)
      echo "Got Event ID:"
      cat $(results.event-listener-event-id.path)
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: tekton-cd-monitor-configmap-cd
  namespace: tektonci
  description: |
    Waits for a configmap CD pipeline to complete and reports the result
spec:
  params:
  - name: eventID
    description: The event ID of the triggered pipeline
  - name: namespace
    description: The namespace where the config map should be deployed
  resources:
    inputs:
      - name: targetCluster
        type: cluster
  stepTemplate:
    env:
    - name: KUBECONFIG
      value: /workspace/$(resources.inputs.targetCluster.name)/kubeconfig
    - name: DASHBOARD_BASE_URL
      value: https://af-tekton2-dff43bc8701fcd5837d6de963718ad39-0000.eu-gb.containers.appdomain.cloud/
    - name: TASKRUN_BASE_NAME
      value: deploy-configmap-github-labels
  steps:
  - name: http-trigger
    image: gcr.io/tekton-releases/dogfooding/kubectl
    script: |
      # Discover the taskrun name
      TASKRUN=$(kubectl -o jsonpath='{.items[0].metadata.name}' \
        get tr -n $(params.namespace) -l 'triggers.tekton.dev/triggers-eventid=$(params.eventID)')

      echo "Waiting for the CD pipelinerun to complete."
      echo "Follow on: ${DASHBOARD_BASE_URL}#/namespaces/$(params.namespace)/taskruns/${TASKRUN}"

      # If the condition was met, the task is successful.
      # If the wait times out or the condition goes to false, the task fails.
      kubectl wait --for=condition=Succeeded \
        taskrun/${TASKRUN} \
        -n $(params.namespace) --timeout=600s
