apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: tekton-plumbing-ci-pipeline
  namespace: tektonci
spec:
  params:
  - name: buildUUID
    description: UUID used to track a CI Pipeline Run in logs
  - name: package
    description: org/repo
  - name: pullRequestNumber
    description: The pullRequestNumber
  - name: pullRequestUrl
    description: The HTML URL for the pull request
  - name: gitRepository
    description: The git repository that hosts context and Dockerfile
  - name: gitRevision
    description: The Git revision to be used.
  - name: gitCloneDepth
    description: Number of commits in the change + 1
  - name: gitHubCommand
    description: |
      The GitHub command that was used a trigger. This is only available when
      this template is triggered by a comment. The default value is for the
      case of a pull_request event.
    default: ""
  - name: githubEvent
    description: GitHub event as provided in the X-GitHub-Event header
  - name: githubAction
    description: GitHub action, for instance "opened" or "synchronize"
  - name: userAgent
    description: User-agent from the pipeline trigger
  - name: labels
    description: List of labels currently on the Pull Request
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      name: plumbing-hub-build-$(uid)
      labels:
        prow.k8s.io/build-id: $(tt.params.buildUUID)
        tekton.dev/check-name: plumbing-hub-build
        tekton.dev/kind: ci
        tekton.dev/pr-number: $(tt.params.pullRequestNumber)
      annotations:
        tekton.dev/gitRevision: "$(tt.params.gitRevision)"
        tekton.dev/gitURL: "$(tt.params.gitRepository)"
    spec:
      serviceAccountName: tekton-ci-jobs
      pipelineRef:
        name: tekton-image-build
      params:
        - name: imageName
          value: hub
        - name: pullRequestNumber
          value: $(tt.params.pullRequestNumber)
        - name: gitCloneDepth
          value: $(tt.params.gitCloneDepth)
        - name: fileFilterRegex
          value: "tekton/images/hub/**"
        - name: checkName
          value: plumbing-hub-build
        - name: gitHubCommand
          value: $(tt.params.gitHubCommand)
        - name: userAgent
          value: $(tt.params.userAgent)
      resources:
      - name: source
        resourceSpec:
          type: git
          params:
          - name: revision
            value: $(tt.params.gitRevision)
          - name: url
            value: $(tt.params.gitRepository)
          - name: depth
            value: $(tt.params.gitCloneDepth)
          - name: userAgent
            value: $(tt.params.userAgent)
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      name: plumbing-kubectl-build-$(uid)
      labels:
        prow.k8s.io/build-id: $(tt.params.buildUUID)
        tekton.dev/check-name: plumbing-kubectl-build
        tekton.dev/kind: ci
        tekton.dev/pr-number: $(tt.params.pullRequestNumber)
      annotations:
        tekton.dev/gitRevision: "$(tt.params.gitRevision)"
        tekton.dev/gitURL: "$(tt.params.gitRepository)"
    spec:
      serviceAccountName: tekton-ci-jobs
      pipelineRef:
        name: tekton-image-build
      params:
        - name: imageName
          value: kubectl
        - name: pullRequestNumber
          value: $(tt.params.pullRequestNumber)
        - name: gitCloneDepth
          value: $(tt.params.gitCloneDepth)
        - name: fileFilterRegex
          value: "tekton/images/kubectl/**"
        - name: checkName
          value: plumbing-kubectl-build
        - name: gitHubCommand
          value: $(tt.params.gitHubCommand)
        - name: userAgent
          value: $(tt.params.userAgent)
      resources:
      - name: source
        resourceSpec:
          type: git
          params:
          - name: revision
            value: $(tt.params.gitRevision)
          - name: url
            value: $(tt.params.gitRepository)
          - name: depth
            value: $(tt.params.gitCloneDepth)
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      name: plumbing-tkn-build-$(uid)
      labels:
        prow.k8s.io/build-id: $(tt.params.buildUUID)
        tekton.dev/check-name: plumbing-tkn-build
        tekton.dev/pr-number: $(tt.params.pullRequestNumber)
        tekton.dev/kind: ci
      annotations:
        tekton.dev/gitRevision: "$(tt.params.gitRevision)"
        tekton.dev/gitURL: "$(tt.params.gitRepository)"
    spec:
      serviceAccountName: tekton-ci-jobs
      pipelineRef:
        name: tekton-image-build
      params:
        - name: imageName
          value: tkn
        - name: pullRequestNumber
          value: $(tt.params.pullRequestNumber)
        - name: gitCloneDepth
          value: $(tt.params.gitCloneDepth)
        - name: fileFilterRegex
          value: "tekton/images/tkn/**"
        - name: checkName
          value: plumbing-tkn-build
        - name: gitHubCommand
          value: $(tt.params.gitHubCommand)
        - name: userAgent
          value: $(tt.params.userAgent)
      resources:
      - name: source
        resourceSpec:
          type: git
          params:
          - name: revision
            value: $(tt.params.gitRevision)
          - name: url
            value: $(tt.params.gitRepository)
          - name: depth
            value: $(tt.params.gitCloneDepth)
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      name: tekton-yamllint-$(uid)
      labels:
        prow.k8s.io/build-id: $(tt.params.buildUUID)
        tekton.dev/check-name: plumbing-yamllint
        tekton.dev/kind: ci
        tekton.dev/pr-number: $(tt.params.pullRequestNumber)
      annotations:
        tekton.dev/gitRevision: "$(tt.params.gitRevision)"
        tekton.dev/gitURL: "$(tt.params.gitRepository)"
    spec:
      serviceAccountName: tekton-ci-jobs
      pipelineRef:
        name: tekton-yamllint
      params:
        - name: pullRequestNumber
          value: $(tt.params.pullRequestNumber)
        - name: gitCloneDepth
          value: $(tt.params.gitCloneDepth)
        - name: fileFilterRegex
          value: ".*"
        - name: checkName
          value: plumbing-yamllint
        - name: gitHubCommand
          value: $(tt.params.gitHubCommand)
        - name: folders
          value: buildbot/config mariobot/config pipelinerun-logs/config boskos gubernator prow robocat tekton
        - name: userAgent
          value: $(tt.params.userAgent)
      resources:
      - name: source
        resourceSpec:
          type: git
          params:
          - name: revision
            value: $(tt.params.gitRevision)
          - name: url
            value: $(tt.params.gitRepository)
          - name: depth
            value: $(tt.params.gitCloneDepth)
