apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: tekton-plumbing-ci-pipeline
  namespace: tektonci
spec:
  params:
  - name: buildUUID
    description: UUID used to track a CI Pipeline Run in logs
  - name: package
    description: org/repo
  - name: pullRequestNumber
    description: The pullRequestNumber
  - name: pullRequestUrl
    description: The HTML URL for the pull request
  - name: gitRepository
    description: The git repository that hosts context and Dockerfile
  - name: gitRevision
    description: The Git revision to be used.
  - name: gitCloneDepth
    description: Number of commits in the change + 1
  - name: gitHubCommand
    description: |
      The GitHub command that was used a trigger. This is only available when
      this template is triggered by a comment. The default value is for the
      case of a pull_request event.
    default: ""
  - name: githubEvent
    description: GitHub event as provided in the X-GitHub-Event header
  - name: githubAction
    description: GitHub action, for instance "opened" or "synchronize"
  - name: userAgent
    description: User-agent from the pipeline trigger
  - name: labels
    description: List of labels currently on the Pull Request
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      name: plumbing-hub-build-$(uid)
      labels:
        prow.k8s.io/build-id: $(tt.params.buildUUID)
        tekton.dev/check-name: plumbing-hub-build
        tekton.dev/kind: ci
        tekton.dev/pr-number: $(tt.params.pullRequestNumber)
      annotations:
        tekton.dev/gitURL: "$(tt.params.gitRepository)"
    spec:
      serviceAccountName: tekton-ci-jobs
      pipelineRef:
        name: tekton-image-build
      params:
        - name: imageName
          value: hub
        - name: pullRequestNumber
          value: $(tt.params.pullRequestNumber)
        - name: gitCloneDepth
          value: $(tt.params.gitCloneDepth)
        - name: fileFilterRegex
          value: "tekton/images/hub/**"
        - name: checkName
          value: plumbing-hub-build
        - name: gitHubCommand
          value: $(tt.params.gitHubCommand)
        - name: userAgent
          value: $(tt.params.userAgent)
      resources:
      - name: source
        resourceSpec:
          type: git
          params:
          - name: revision
            value: $(tt.params.gitRevision)
          - name: url
            value: $(tt.params.gitRepository)
          - name: depth
            value: $(tt.params.gitCloneDepth)
          - name: userAgent
            value: $(tt.params.userAgent)
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      name: plumbing-kubectl-build-$(uid)
      labels:
        prow.k8s.io/build-id: $(tt.params.buildUUID)
        tekton.dev/check-name: plumbing-kubectl-build
        tekton.dev/kind: ci
        tekton.dev/pr-number: $(tt.params.pullRequestNumber)
      annotations:
        tekton.dev/gitURL: "$(tt.params.gitRepository)"
    spec:
      serviceAccountName: tekton-ci-jobs
      pipelineRef:
        name: tekton-image-build
      params:
        - name: imageName
          value: kubectl
        - name: pullRequestNumber
          value: $(tt.params.pullRequestNumber)
        - name: gitCloneDepth
          value: $(tt.params.gitCloneDepth)
        - name: fileFilterRegex
          value: "tekton/images/kubectl/**"
        - name: checkName
          value: plumbing-kubectl-build
        - name: gitHubCommand
          value: $(tt.params.gitHubCommand)
        - name: userAgent
          value: $(tt.params.userAgent)
      resources:
      - name: source
        resourceSpec:
          type: git
          params:
          - name: revision
            value: $(tt.params.gitRevision)
          - name: url
            value: $(tt.params.gitRepository)
          - name: depth
            value: $(tt.params.gitCloneDepth)
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      name: plumbing-tkn-build-$(uid)
      labels:
        prow.k8s.io/build-id: $(tt.params.buildUUID)
        tekton.dev/check-name: plumbing-tkn-build
        tekton.dev/kind: ci
        tekton.dev/pr-number: $(tt.params.pullRequestNumber)
      annotations:
        tekton.dev/gitURL: "$(tt.params.gitRepository)"
    spec:
      serviceAccountName: tekton-ci-jobs
      pipelineRef:
        name: tekton-image-build
      params:
        - name: imageName
          value: tkn
        - name: pullRequestNumber
          value: $(tt.params.pullRequestNumber)
        - name: gitCloneDepth
          value: $(tt.params.gitCloneDepth)
        - name: fileFilterRegex
          value: "tekton/images/tkn/**"
        - name: checkName
          value: plumbing-tkn-build
        - name: gitHubCommand
          value: $(tt.params.gitHubCommand)
        - name: userAgent
          value: $(tt.params.userAgent)
      resources:
      - name: source
        resourceSpec:
          type: git
          params:
          - name: revision
            value: $(tt.params.gitRevision)
          - name: url
            value: $(tt.params.gitRepository)
          - name: depth
            value: $(tt.params.gitCloneDepth)
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      name: tekton-golang-lint-$(uid)
      labels:
        prow.k8s.io/build-id: $(tt.params.buildUUID)
        tekton.dev/check-name: plumbing-golang-lint
        tekton.dev/kind: ci
        tekton.dev/pr-number: $(tt.params.pullRequestNumber)
      annotations:
        tekton.dev/gitURL: "$(tt.params.gitRepository)"
    spec:
      serviceAccountName: tekton-ci-jobs
      pipelineRef:
        name: tekton-golang-lint
      params:
        - name: pullRequestNumber
          value: $(tt.params.pullRequestNumber)
        - name: gitCloneDepth
          value: $(tt.params.gitCloneDepth)
        - name: fileFilterRegex
          value: ".*"
        - name: checkName
          value: plumbing-golang-lint
        - name: gitHubCommand
          value: $(tt.params.gitHubCommand)
        - name: userAgent
          value: $(tt.params.userAgent)
      resources:
      - name: source
        resourceSpec:
          type: git
          params:
          - name: revision
            value: $(tt.params.gitRevision)
          - name: url
            value: $(tt.params.gitRepository)
          - name: depth
            value: $(tt.params.gitCloneDepth)
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      name: plumbing-test-tekton-ci-$(uid)
      labels:
        prow.k8s.io/build-id: $(tt.params.buildUUID)
        tekton.dev/check-name: plumbing-test-tekton-ci
        tekton.dev/kind: ci
        tekton.dev/pr-number: $(tt.params.pullRequestNumber)
      annotations:
        tekton.dev/gitURL: "$(tt.params.gitRepository)"
        ci.tekton.dev/github-delivery: $(tt.params.buildUUID)
        ci.tekton.dev/github-repo: $(tt.params.package)
        ci.tekton.dev/github-event: $(tt.params.githubEvent)
        ci.tekton.dev/github-action: $(tt.params.githubAction)
        ci.tekton.dev/github-pr-number: $(tt.params.pullRequestNumber)
        ci.tekton.dev/github-git-revision: $(tt.params.gitRevision)
        ci.tekton.dev/git-clone-depth: $(tt.params.gitCloneDepth)
    spec:
      serviceAccountName: tekton-ci-jobs
      pipelineRef:
        name: test-resource-folder
      params:
        - name: gitCloneDepth
          value: $(tt.params.gitCloneDepth)
        - name: fileFilterRegex
          value: "tekton/ci/**"
        - name: checkName
          value: plumbing-test-tekton-ci
        - name: gitHubCommand
          value: $(tt.params.gitHubCommand)
        - name: namespace
          value: pr$(tt.params.pullRequestNumber)-$(uid)
        - name: folderPath
          value: "tekton/ci"
        - name: userAgent
          value: $(tt.params.userAgent)
      resources:
      - name: target
        resourceRef:
          name: af-tekton-cadmin
      - name: source
        resourceSpec:
          type: git
          params:
          - name: revision
            value: $(tt.params.gitRevision)
          - name: url
            value: $(tt.params.gitRepository)
          - name: depth
            value: $(tt.params.gitCloneDepth)
      - name: cloudEventTarget
        resourceSpec:
          type: cloudEvent
          params:
            - name: targetURI
              value: http://el-tekton-ci-webhook.pr$(tt.params.pullRequestNumber)-$(uid):8080
