apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: tekton-cd-triggers
  namespace: tektonci
spec:
  params:
  - name: buildUUID
    description: UUID used to track a CI Pipeline Run in logs
  - name: package
    description: org/repo
  - name: pullRequestNumber
    description: The pullRequestNumber
  - name: gitRepository
    description: The git repository that hosts context and Dockerfile
  - name: gitRevision
    description: The Git revision to be used.
  - name: gitCloneDepth
    description: Number of commits in the change + 1
  - name: gitHubCommand
    description: |
      The GitHub command that was used a trigger. This is only available when
      this template is triggered by a comment. The default value is for the
      case of a pull_request event.
    default: ""
  - name: githubEvent
    description: GitHub event as provided in the X-GitHub-Event header
  - name: githubAction
    description: GitHub action, for instance "opened" or "synchronize"
  - name: userAgent
    description: User-agent from the pipeline trigger
  - name: labels
    description: List of labels currently on the Pull Request
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      name: plumbing-test-tekton-cd-$(uid)
      labels:
        prow.k8s.io/build-id: $(tt.params.buildUUID)
        tekton.dev/check-name: plumbing-test-tekton-cd
        tekton.dev/pr-number: $(tt.params.pullRequestNumber)
        tekton.dev/kind: ci-infra
      annotations:
        tekton.dev/gitURL: "$(tt.params.gitRepository)"
        ci.tekton.dev/github-delivery: $(tt.params.buildUUID)
        ci.tekton.dev/github-repo: $(tt.params.package)
        ci.tekton.dev/github-event: $(tt.params.githubEvent)
        ci.tekton.dev/github-action: $(tt.params.githubAction)
        ci.tekton.dev/github-pr-number: $(tt.params.pullRequestNumber)
        ci.tekton.dev/github-git-revision: $(tt.params.gitRevision)
        ci.tekton.dev/git-clone-depth: $(tt.params.gitCloneDepth)
    spec:
      serviceAccountName: tekton-ci-jobs
      pipelineRef:
        name: test-resource-cd-folder
      params:
        - name: gitCloneDepth
          value: $(tt.params.gitCloneDepth)
        - name: fileFilterRegex
          value: "tekton/resources/cd/**"
        - name: checkName
          value: plumbing-test-tekton-cd
        - name: gitHubCommand
          value: $(tt.params.gitHubCommand)
        - name: namespace
          value: pr$(tt.params.pullRequestNumber)-cd-$(uid)
        - name: folderPath
          value: "tekton/resource/cd"
        - name: userAgent
          value: $(tt.params.userAgent)
      resources:
      - name: target
        resourceRef:
          name: af-tekton-cadmin
      - name: source
        resourceSpec:
          type: git
          params:
          - name: revision
            value: $(tt.params.gitRevision)
          - name: url
            value: $(tt.params.gitRepository)
          - name: depth
            value: $(tt.params.gitCloneDepth)
      - name: baseSource
        resourceSpec:
          type: git
          params:
          - name: revision
            value: master
          - name: url
            value: $(tt.params.gitRepository)
          - name: depth
            value: "1"
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      name: cd-configmap-labels-trigger-$(uid)
      labels:
        prow.k8s.io/build-id: $(tt.params.buildUUID)
        tekton.dev/check-name: plumbing-configmap-cd-test
        tekton.dev/kind: ci
        tekton.dev/pr-number: $(tt.params.pullRequestNumber)
      annotations:
        tekton.dev/gitURL: "$(tt.params.gitRepository)"
        tekton.dev/gitRevision: "$(tt.params.gitRevision)"
        ci.tekton.dev/github-delivery: $(tt.params.buildUUID)
        ci.tekton.dev/github-repo: $(tt.params.package)
        ci.tekton.dev/github-event: $(tt.params.githubEvent)
        ci.tekton.dev/github-action: $(tt.params.githubAction)
        ci.tekton.dev/github-pr-number: $(tt.params.pullRequestNumber)
        ci.tekton.dev/github-git-revision: $(tt.params.gitRevision)
        ci.tekton.dev/git-clone-depth: $(tt.params.gitCloneDepth)
    spec:
      serviceAccountName: tekton-ci-jobs
      pipelineRef:
        name: cd-configmap-labels-trigger
      resources:
        - name: source
          resourceSpec:
            type: git
            params:
            - name: revision
              value: $(tt.params.gitRevision)
            - name: url
              value: $(tt.params.gitRepository)
            - name: depth
              value: $(tt.params.gitCloneDepth)
        - name: targetCluster
          resourceRef:
            name: "af-tekton-cadmin"
      params:
        - name: gitCloneDepth
          value: $(tt.params.gitCloneDepth)
        - name: fileFilterRegex
          value: "tekton/resources/cd/configmap-template.yaml"
        - name: checkName
          value: plumbing-configmap-cd-test
        - name: gitHubCommand
          value: $(tt.params.gitHubCommand)
        - name: userAgent
          value: $(tt.params.userAgent)
        - name: gitRevision
          value: $(tt.params.gitRevision)
        - name: namespace
          value: pr$(tt.params.pullRequestNumber)-cd-$(uid)
