---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: tekton-ci-webhook
  namespace: tektonci
spec:
  serviceAccountName: tekton-ci-listener
  serviceType: LoadBalancer
  triggers:
    - name: plumbing-pull-request-ci
      interceptors:
        - github:
            secretRef:
              secretName: ci-webhook
              secretKey: secret
            eventTypes:
              - pull_request
        - cel:
            filter: >-
              body.repository.full_name == 'andreafrittoli/plumbing' &&
              (body.action == 'opened' || body.action == 'synchronize')
            overlays:
            - key: extensions.git_clone_depth
              expression: "string(body.pull_request.commits + 1.0)"
      bindings:
        - ref: tekton-ci-github-base
        - ref: tekton-ci-webhook-pull-request
        - ref: tekton-ci-clone-depth
        - ref: tekton-ci-webhook-pr-labels
      template:
        name: tekton-plumbing-ci-pipeline
    - name: all-comment-ci
      interceptors:
        - github:
            secretRef:
              secretName: ci-webhook
              secretKey: secret
            eventTypes:
              - issue_comment
        - cel:
            filter: >-
              body.repository.full_name.startsWith('andreafrittoli/') &&
              body.repository.name in ['plumbing', 'pipeline', 'triggers', 'cli', 'dashboard', 'catalog', 'hub'] &&
              body.action == 'created' &&
              'pull_request' in body.issue &&
              body.issue.state == 'open' &&
              body.comment.body.matches('^/test($| [^ ]*[ ]*$)')
            overlays:
            - key: add_pr_body.pull_request_url
              expression: "body.issue.pull_request.url"
        - webhook:
            objectRef:
              kind: Service
              name: add-pr-body
              apiVersion: v1
              namespace: tektonci
        - cel:
            overlays:
            - key: extensions.git_clone_depth
              expression: "string(body.add_pr_body.pull_request_body.commits + 1.0)"
      bindings:
        - ref: tekton-ci-github-base
        - ref: tekton-ci-webhook-comment
        - ref: tekton-ci-clone-depth
        - ref: tekton-ci-webhook-pr-labels
      template:
        name: tekton-plumbing-ci-pipeline
    - name: all-pull-request-check-pr-labels
      interceptors:
        - github:
            secretRef:
              secretName: ci-webhook
              secretKey: secret
            eventTypes:
              - pull_request
        - cel:
            filter: >-
              body.repository.full_name.startsWith('tektoncd/') &&
              body.repository.name in ['plumbing', 'pipeline', 'triggers', 'cli', 'dashboard', 'catalog', 'hub'] &&
              (body.action == 'opened' ||
               body.action == 'synchronize' ||
               body.action == 'labeled' ||
               body.action == 'unlabeled')
            overlays:
            - key: extensions.pr_number
              expression: body.pull_request.html_url.split('/')[size(body.pull_request.html_url.split('/'))-1]
      bindings:
        - ref: tekton-ci-github-base
        - ref: tekton-ci-pr-number-extension
        - ref: tekton-ci-webhook-pr-labels
      template:
        name: check-pull-request-labels
    - name: test-ci-trigger
      interceptors:
        - cel:
            filter: >-
              body.taskRun.metadata.annotations['ci.tekton.dev/github-repo'] == 'andreafrittoli/plumbing' &&
              ((body.taskRun.metadata.annotations['ci.tekton.dev/github-event'] == 'pull_request' &&
              body.taskRun.metadata.annotations['ci.tekton.dev/github-action'] in ['opened', 'synchronize']) ||
              (body.taskRun.metadata.annotations['ci.tekton.dev/github-event'] == 'issue_comment' &&
              body.taskRun.metadata.annotations['ci.tekton.dev/github-action'] in ['created', 'updated']))
      bindings:
        - ref: tekton-ci-github-base-forwarded
        - ref: tekton-ci-webhook-pull-request-forwarded
        - ref: tekton-ci-clone-depth-forwarded
      template:
        name: tekton-plumbing-ci-pipeline
    - name: cd-trigger
      interceptors:
        - github:
            secretRef:
              secretName: ci-webhook
              secretKey: secret
            eventTypes:
              - issue_comment
        - cel:
            filter: >-
              body.repository.name in ['plumbing', 'pipeline', 'triggers', 'cli', 'dashboard', 'catalog', 'hub'] &&
              body.action == 'created' &&
              'pull_request' in body.issue &&
              body.issue.state == 'open' &&
              body.comment.body.matches('^/tektoncd($| [^ ]*[ ]*$)')
            overlays:
            - key: add_team_members.org_base_url
              expression: "body.organization.url"
            - key: add_team_members.team
              expression: "body.repository.name"
        - webhook:
            objectRef:
              kind: Service
              name: add-team-member
              apiVersion: v1
              namespace: tektonci
        - cel:
            filter: >-
              body.comment.user.login in body.add_team_members.maintainers_team_members
      bindings:
        - ref: tekton-ci-github-base
        - ref: tekton-ci-webhook-tektoncd-comment
      template:
        name: tekton-cd-triggers
